### ISSUE TITLE
Skip file overwrite if output is identical

### ISSUE THREAD

**Issue by vlsi** [raydac/java-comment-preprocessor#1] opened 2015-11-28 11:50 UTC
Currently java-comment-preprocessor always overwrites files, so java compiler always recompiles all the files.

Can JCP doublecheck if output is good enough and avoid file overwrites?

**Comment by raydac** [comment] 2015-11-28 11:56
I think it is possible to implement such feature

**Comment by vlsi** [comment] 2015-11-28 11:58
"maven-source-plugin" Invokes the execution of the lifecycle phase generate-sources prior to executing itself, thus if using maven-source-plugin and java-comment-preprocessor at the same time it forces maven to recompile the project twice.

**Comment by vlsi** [comment] 2015-11-28 12:01
By the way: I like how smooth JCP integration was.

I use it to support multiple JDK versions for PostgreSQL JDBC driver: https://github.com/pgjdbc/pgjdbc/pull/435.
It's just very basic "comment out `java.sql.SQLType` usage for JDK<1.8" stuff, and I like how JCP keeps line numbers intact.

**Comment by raydac** [comment] 2015-11-28 20:45
I have added --z parameter into CLI and compareDestination into MAVEN and ANT https://github.com/raydac/java-comment-preprocessor/commit/f63d1ad539acd8ed29a43c8e0a0a39d95b5fa22b
you can try the snapshot

**Comment by vlsi** [comment] 2015-11-28 21:01
Do you mean snapshot version is deployed somewhere?
Or should I build it from the sources?

**Comment by raydac** [comment] 2015-11-28 21:11
you can build from sources or use brebuilt version https://drive.google.com/file/d/0BxHnNp97IgMRX05LZXNtbEVhZEE/view?usp=sharing

**Comment by vlsi** [comment] 2015-11-28 21:23
f63d1ad works for me.

```
[INFO] Preprocess sources : /Users/vladimirsitnikov/Documents/code/pgjdbc2/core/src/main/java
[INFO] Preprocess destination : /Users/vladimirsitnikov/Documents/code/pgjdbc2/core/target/gen-src
[INFO] -----------------------------------------------------------------
[INFO] Completed, preprocessed 158 files, copied 0 files, elapsed time 403ms
[INFO] A Compile source root has been removed from the root list [/Users/vladimirsitnikov/Documents/code/pgjdbc2/core/src/main/java]
[INFO] The New compile source root has been added into the list [/Users/vladimirsitnikov/Documents/code/pgjdbc2/core/target/gen-src]
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ postgresql ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 16 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ postgresql ---
[INFO] Nothing to compile - all classes are up to date
```


FYI: build without `-DskipTests` fails for me as follows:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.igormaznitsa.jcp.it.ant.ITAntTask
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.218 sec - in com.igormaznitsa.jcp.it.ant.ITAntTask
Running com.igormaznitsa.jcp.it.maven.ITPreprocessorMojo
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.073 sec <<< FAILURE! - in com.igormaznitsa.jcp.it.maven.ITPreprocessorMojo
com.igormaznitsa.jcp.it.maven.ITPreprocessorMojo  Time elapsed: 0.072 sec  <<< ERROR!
org.apache.maven.it.VerificationException:
Failed to execute Maven: Failed to run Maven: Error while executing process.
/Users/vladimirsitnikov/Programs/apache-maven-3.3.9/bin/mvn -Dfile=/Users/vladimirsitnikov/Documents/work/java-comment-preprocessor/target/jcp-6.0.1-SNAPSHOT.jar -DpomFile=/Users/vladimirsitnikov/Documents/work/java-comment-preprocessor/pom.xml -e --batch-mode -Dmaven.repo.local=/Users/vladimirsitnikov/.m2/repository org.apache.maven.plugins:maven-clean-plugin:clean install:install-file
	at com.igormaznitsa.jcp.it.maven.ITPreprocessorMojo.setUpBeforeClass(ITPreprocessorMojo.java:65)
Caused by: org.apache.maven.it.LauncherException:
Failed to run Maven: Error while executing process.
/Users/vladimirsitnikov/Programs/apache-maven-3.3.9/bin/mvn -Dfile=/Users/vladimirsitnikov/Documents/work/java-comment-preprocessor/target/jcp-6.0.1-SNAPSHOT.jar -DpomFile=/Users/vladimirsitnikov/Documents/work/java-comment-preprocessor/pom.xml -e --batch-mode -Dmaven.repo.local=/Users/vladimirsitnikov/.m2/repository org.apache.maven.plugins:maven-clean-plugin:clean install:install-file
	at com.igormaznitsa.jcp.it.maven.ITPreprocessorMojo.setUpBeforeClass(ITPreprocessorMojo.java:65)
Caused by: org.apache.maven.it.util.cli.CommandLineException: Error while executing process.
	at com.igormaznitsa.jcp.it.maven.ITPreprocessorMojo.setUpBeforeClass(ITPreprocessorMojo.java:65)
Caused by: java.io.IOException: Cannot run program "/Users/vladimirsitnikov/Programs/apache-maven-3.3.9/bin/mvn" (in directory "/Users/vladimirsitnikov/Documents/work/java-comment-preprocessor/target/test-classes/com/igormaznitsa/jcp/it/maven/dummy_maven_project"): error=2, No such file or directory
	at com.igormaznitsa.jcp.it.maven.ITPreprocessorMojo.setUpBeforeClass(ITPreprocessorMojo.java:65)
Caused by: java.io.IOException: error=2, No such file or directory
	at com.igormaznitsa.jcp.it.maven.ITPreprocessorMojo.setUpBeforeClass(ITPreprocessorMojo.java:65)


Results :

Tests in error:
  ITPreprocessorMojo.setUpBeforeClass:65 » Verification Failed to execute Maven:...
```

**Comment by raydac** [comment] 2015-11-28 21:28
the plug-in has a bit bizarre build process and you should have maven distributive on your machine and the way to the distributive should be directly placed into maven.home property in the pom.xml, it starts maven during integration tests

**Comment by vlsi** [comment] 2015-11-28 21:31
I see.

I just did a test via jitpack.io just for fun and it does not work:
https://jitpack.io/#raydac/java-comment-preprocessor/4238e69afd

```
Downloading: https://jitpack.io/com/github/raydac/java-comment-preprocessor/4238e69afd/java-comment-preprocessor-4238e69afd.pom
Downloaded: https://jitpack.io/com/github/raydac/java-comment-preprocessor/4238e69afd/java-comment-preprocessor-4238e69afd.pom (13 KB at 0.3 KB/sec)
Downloading: https://jitpack.io/com/github/raydac/java-comment-preprocessor/4238e69afd/java-comment-preprocessor-4238e69afd.jar
Downloaded: https://jitpack.io/com/github/raydac/java-comment-preprocessor/4238e69afd/java-comment-preprocessor-4238e69afd.jar (848 KB at 1002.8 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.995 s
[INFO] Finished at: 2015-11-29T00:29:50+03:00
[INFO] Final Memory: 11M/205M
[INFO] ------------------------------------------------------------------------
[ERROR] Invalid plugin descriptor for com.github.raydac:java-comment-preprocessor:4238e69afd (/Users/vladimirsitnikov/.m2/repository/com/github/raydac/java-comment-preprocessor/4238e69afd/java-comment-preprocessor-4238e69afd.jar), Plugin's descriptor contains the wrong group ID: com.igormaznitsa, Plugin's descriptor contains the wrong artifact ID: jcp, Plugin's descriptor contains the wrong version: 6.0.1-SNAPSHOT -> [Help 1]
```

**Comment by jitpack-io** [comment] 2015-11-30 17:01
Hi @vlsi 

Probably the issue is that JitPack rewrites groupId/artifactId to match the GitHub repository. Guessing that the original groupId is specified in the plugin descriptor.

**Comment by vlsi** [comment] 2015-12-06 20:37
@raydac , would you mind releasing 6.0.1?

**Comment by raydac** [comment] 2015-12-06 20:49
@vlsi it works well?

**Comment by vlsi** [comment] 2015-12-06 20:52
it does as in log above: https://github.com/raydac/java-comment-preprocessor/issues/1#issuecomment-160336634

**Comment by raydac** [comment] 2015-12-07 10:30
I have moved integration tests into special profile and at present anyone should not have problems to build version locally

**Comment by vlsi** [comment] 2015-12-07 10:34
JFY: that solves `mvn install` for me:
```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ jcp ---
[INFO] Installing /.../java-comment-preprocessor/target/jcp-6.0.1-SNAPSHOT.jar to /.../.m2/repository/com/igormaznitsa/jcp/6.0.1-SNAPSHOT/jcp-6.0.1-SNAPSHOT.jar
[INFO] Installing /.../java-comment-preprocessor/dependency-reduced-pom.xml to /.../.m2/repository/com/igormaznitsa/jcp/6.0.1-SNAPSHOT/jcp-6.0.1-SNAPSHOT.pom
[INFO] Installing /.../java-comment-preprocessor/target/jcp-6.0.1-SNAPSHOT-sources.jar to /.../.m2/repository/com/igormaznitsa/jcp/6.0.1-SNAPSHOT/jcp-6.0.1-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.246 s
[INFO] Finished at: 2015-12-07T13:32:43+03:00
[INFO] Final Memory: 43M/1022M
```

**Comment by raydac** [comment] 2015-12-07 11:43
@vlsi so how is your opinion? is it ready to be released as 6.0.1 in current state?

**Comment by vlsi** [comment] 2015-12-07 12:03
@raydac , it looks like it does not work.
Previously I only tested that "subsequent processing" do not update files, however now I see that if I delete `target/gen-src`, then jcp is not healing the files.

Here's what i get with `<verbose>true</verbose>` (it would be better to set `verbose=true` when `mvn -X` detected).

Just "Content was not saved " with no explanation.

```
[INFO] Start search global definitions in '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/ssl/NonValidatingFactory.java'
[INFO] Global search completed for file '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/ssl/NonValidatingFactory.java', elapsed time 0ms.
[INFO] Start search global definitions in '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java'
[INFO] Global search completed for file '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/jdbc/PgResultSet.java', elapsed time 4ms.
[INFO] Start search global definitions in '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java'
[INFO] Global search completed for file '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/core/v3/ConnectionFactoryImpl.java', elapsed time 1ms.
[INFO] Start preprocessing '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/core/TypeInfo.java'
[INFO] Content was not saved into file '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/target/gen-src/org/postgresql/core/TypeInfo.java'.
[INFO] File preprocessing completed  '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/core/TypeInfo.java', elapsed time 5ms.
[INFO] Start preprocessing '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java'
[INFO] Content was not saved into file '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/target/gen-src/org/postgresql/jdbc/TimestampUtils.java'.
[INFO] File preprocessing completed  '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/jdbc/TimestampUtils.java', elapsed time 6ms.
[INFO] Start preprocessing '/Users/vladimirsitnikov/Documents/code/pgjdbc-all/pgjdbc/pgjdbc/src/main/java/org/postgresql/util/PGTimestamp.java'
```

**Comment by vlsi** [comment] 2015-12-07 12:20
I believe, the fix is https://github.com/raydac/java-comment-preprocessor/pull/5

**Comment by raydac** [comment] 2015-12-07 13:04
@vlsi I have merged the fix and also I have improved logging for debugging, now it will be written into debug log if the file content was not rewritten because its content was not changed, also verbose level is activated  automatically  if maven debug level is active

**Comment by vlsi** [comment] 2015-12-08 13:40
@raydac , it works fine for me

**Closed** 2015-12-08 20:25 UTC
Labels: enhancement
